[tool.poetry]
name = "pyprince"
version = "0.1.0"
description = ""
authors = ["HMate <mhidvegi@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9, <3.13"
libcst = "^0.4.0"
typer = "^0.3.2"
fs = "^2.4.13"
orjson = "^3.6.3"
rich = "^13.4.2"

[tool.poetry.dev-dependencies]
black = { version = "^20.8b1", allow-prereleases = true }
pytest = "^6.2.3"
pylint = "^2.8.3"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.13.0"
stdlib-list = "^0.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120