[tool.poetry]
name = "pyprince"
version = "0.1.0"
description = ""
authors = ["HMate <mhidvegi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
libcst = "^0.3.18"
typer = "^0.3.2"
fs = "^2.4.13"
pylint = "^2.8.3"
pyvis = "^0.1.9"

[tool.poetry.dev-dependencies]
black = { version = "^20.8b1", allow-prereleases = true }
pytest = "^6.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120